title: ToxiCactus
baseurl: "/toxicactus" 
url: "https://votreusername.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default
      comments: true
